### ISSUE TITLE
where to find "haiti_cholera_locations_072018.csv" file?

### ISSUE THREAD

**Issue by liamxg** [taylorpaisie/data_analysis_scripts#1]
Dear @taylorpaisie,

Could I know where to find "haiti_cholera_locations_072018.csv" file? Thanks.

Best,
Liam

**Comment by taylorpaisie** [comment]
Sorry its been a while since i've worked with these scripts, so not sure what script this file is located in, although I know I don't have access to that specific file anymore.

**Comment by liamxg** [comment]
Dear @taylorpaisie,

Thanks for letting me know this.

Best,
Liam
